version: "3"
services:
  web:
    build: .
    container_name: myflaskapp 
    image: ghcr.io/litostitos/flask-app
    ports:
      - "5009:5000"
    volumes:
      - .:/app  
      - ./instance:/app/instance